/**
 * Vendor-copy drift fence: codex-channel ships byte-identical snapshots of
 * the shared openclaw-channel modules so its packaged artifact is
 * self-contained. In a full-repo checkout the canonical files exist and MUST
 * equal the vendor copies (refresh with `node scripts/sync-codex-vendor.mjs`).
 * In an isolated artifact the canonical files are absent and the check
 * skips — the snapshot IS the runtime there.
 */

import assert from "node:assert/strict";
import test from "node:test";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(pkgRoot, "..");

const PAIRS = [
  ["openclaw-channel/src/envelope.js", "src/vendor/openclaw-envelope.js"],
  ["openclaw-channel/src/outbound.js", "src/vendor/openclaw-outbound.js"],
  // mcp-server artifact vendor snapshots (generated by its npm prebuild).
  ["lib/relay-expand-store.js", "../mcp-server/vendor/relay-expand-store.js"],
  ["lib/relay-notice.js", "../mcp-server/vendor/relay-notice.js"],
];

for (const [canonicalRel, vendorRel] of PAIRS) {
  test(`vendor parity: ${vendorRel} matches ${canonicalRel}`, (t) => {
    const canonical = join(repoRoot, canonicalRel);
    const vendor = join(pkgRoot, vendorRel);
    assert.ok(existsSync(vendor), `vendor copy missing: ${vendor}`);
    if (!existsSync(canonical)) {
      t.skip("canonical source absent (isolated artifact) — snapshot is authoritative");
      return;
    }
    assert.equal(
      readFileSync(vendor, "utf8"),
      readFileSync(canonical, "utf8"),
      `vendor copy drifted from canonical — run: node scripts/sync-codex-vendor.mjs`,
    );
  });
}
